#!/bin/sh
. /usr/lib/liveos/common.sh
guard; json_head
KERNEL=$(uname -r)
MEM=$(awk '/MemTotal/{printf "%d MB", $2/1024}' /proc/meminfo)
UP=$(awk '{s=int($1); printf "%dh %dmin", s/3600, (s%3600)/60}' /proc/uptime)
IF=$(wifi_if)
IP=$(ip -4 -o addr show "$IF" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1)
printf '{"kernel":"%s","mem":"%s","uptime":"%s","ip":"%s"}' "$KERNEL" "$MEM" "$UP" "$IP"
